#!/bin/bash

#võtab failinime ning teeb iga rea failist kasutajaks kasutades lisa_kasutaja faili

if [ $# -ne 1 ];then
echo "ei"

else
fail=$1

if [ -f $fail -a -r $fail ]; then
echo "Fail on korras"

for nimi in $(cat $fail)
do
sh lisa_kasutaja $nimi
done

else
echo "Probleem failiga $fail"
fi
fi
