#!/bin/bash

#loeb sisestatud kasutajanime ning teeb selle põhjal kasutaja ja /home kataloogi(vajalike peidetud failidega)

echo -n "Sisestage kasutajanimi kasutajale, mida soovite luua:"
read nimi

#teeb kasutaja
sudo useradd $nimi -m -s /bin/bash
tulemus=$?

#kui kõik on korras
if [ $tulemus -eq 0 ]; then
echo "Kasutaja nimega $nimi on tehtud"
cat /etc/passwd | grep $nimi
ls -la /home/$nimi

#kui on probleeme
else
echo "Probleem kasutaja $nimi lisamisel"
echo "probleemi kood on $tulemus"
fi

